### ISSUE TITLE
Bot injection attacks produce distracting error email

### ISSUE THREAD

**Issue by dmolesUC3** [CDLUC3/mrt-dashboard#13]
Since this isn't telling us about an error in our app, we should just log it without bothering to send the email.

A typical example:

```
An ArgumentError occurred in collection#index:

  invalid value for Integer(): "314'A=0"
  /apps/dpr2/local/lib/ruby/2.4.0/delegate.rb:85:in `Integer'


-------------------------------
Request:
-------------------------------

  * URL        : http://merritt.cdlib.org/m/ucd_ice_swap?page=314'A=0
  * HTTP Method: GET
  * IP address : 188.162.43.244
  * Parameters : {"page"=>"314'A=0", "controller"=>"collection", "action"=>"index", "group"=>"ucd_ice_swap"}
  * Timestamp  : 2018-07-17 06:43:02 UTC
  * Server : uc3-mrtui03-prd
  * Rails root : /apps/dpr2/apps/ui/releases/20180711184350
  * Process: 18688

-------------------------------
Session:
-------------------------------

  * session id: "6fda3e48f20ed20656a8e6903242e592"
  * data: {"session_id"=>"6fda3e48f20ed20656a8e6903242e592",
   "flash"=>{"discard"=>[], "flashes"=>{"notice"=>"Login was successful"}},
   "expiry_time"=>2018-07-16 23:43:00 -0700,
   "uid"=>"anonymous",
   "group_id"=>"ucd_ice_swap",
   "group_ark"=>"ark:/13030/m5dz06hz",
   "group_description"=>"UC Davis ICE: Source Water Assessment Program"}

-------------------------------
Environment:
-------------------------------

  * CONTENT_TYPE                                   : text/html; charset=utf-8
  * GATEWAY_INTERFACE                              : CGI/1.2
  * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate
  * HTTP_CONNECTION                                : Keep-Alive
  * HTTP_COOKIE                                    : _mrt-dash_session=S3pmUE84djQrMnVRbW9xSTQ0R3JYSGdaVDdZZzZoMFIyVWxUb0ZHckNOU3U1YjIzK2dkQmxaYjVCRDZ0ZHl5NXdpYk42SXEvblVJTWoxY1h6cjR5YTNaWVFUanA2Q0c1RmJVelo3WU5jVEh2ZHl2WFc1OHExUGNIM2lueTBSZGt0WW9ndUZTRmtzd3V0ZXExRlBVZlp1WTBYT1ZGd25OSU9DS2x3d1NWNWJWcHRIVHNndGsvWDc0dG5KWVZnMmR5UzlIcFBTb20xeEhHbGNNbjA5dFBwbUVUSEVFdzAyOTBaeEltUHY5SGg0VCs0VVQ2VFQyU3pPYUx2YURHS1FvYTh5bC9vMVBjUHFOc3puS3lKd3c1UVd0SjJFUUY1K2d2QTZiaklwQVJFWDZQakZHWFBHbDdMajNHYlBvMmFWMXdPUVg3Q0ptOHY3VnVPelA4NzMxblptcC9kbm1UbUlibXBjK0t4aDI5V1JFSzd3bHFpajJqeGwvdVBZeDZxSE9aLS1sSENEczVUQUpVWkgzR0pFajdPS2JnPT0%3D--3d4f6f77902c2e303eb220b37f66d860c813c50d
  * HTTP_HOST                                      : ui03-aws.cdlib.org:26181
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows; U; Windows NT 5.1; pt-PT; rv:1.9.1.2) Gecko/20090729 Firefox/3.5.2 (.NET CLR 3.5.30729)
  * HTTP_VERSION                                   : HTTP/1.1
  * HTTP_X_FORWARDED_FOR                           : 188.162.43.244
  * HTTP_X_FORWARDED_HOST                          : merritt.cdlib.org
  * HTTP_X_FORWARDED_SERVER                        : merritt.cdlib.org
  * ORIGINAL_FULLPATH                              : /m/ucd_ice_swap?page=314'A=0
  * ORIGINAL_SCRIPT_NAME                           :
  * PATH_INFO                                      : /m/ucd_ice_swap
  * QUERY_STRING                                   : page=314'A=0
  * REMOTE_ADDR                                    : 172.30.22.60
  * REQUEST_METHOD                                 : GET
  * REQUEST_PATH                                   : /m/ucd_ice_swap
  * REQUEST_URI                                    : /m/ucd_ice_swap?page=314'A=0
  * ROUTES_46961557442140_SCRIPT_NAME              :
  * SCRIPT_NAME                                    :
  * SERVER_NAME                                    : ui03-aws.cdlib.org
  * SERVER_PORT                                    : 26181
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : puma 3.8.2 Sassy Salamander
  * action_controller.instance                     : #<CollectionController:0x00007fc63d5c9738>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x0000556c2f03aed0>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x00007fc63d5c7d48>
  * action_dispatch.cookies_digest                 :
  * action_dispatch.cookies_serializer             :
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x0000556c2f37f5a0>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x0000556c2de0e590>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 188.162.43.244
  * action_dispatch.request.content_type           : text/html
  * action_dispatch.request.formats                : [#<Mime::Type:0x0000556c2de165b0 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-1496065919452742067>]
  * action_dispatch.request.parameters             : {"page"=>"314'A=0", "controller"=>"collection", "action"=>"index", "group"=>"ucd_ice_swap"}
  * action_dispatch.request.path_parameters        : {:controller=>"collection", :action=>"index", :group=>"ucd_ice_swap"}
  * action_dispatch.request.query_parameters       : {"page"=>"314'A=0"}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"6fda3e48f20ed20656a8e6903242e592", "flash"=>{"discard"=>[], "flashes"=>{"notice"=>"Login was successful"}}, "expiry_time"=>2018-07-16 23:43:00 -0700, "uid"=>"anonymous"}
  * action_dispatch.request_id                     : 78792957-e924-478f-9ec4-c4adb9986ab1
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x0000556c2de61cb8>
  * action_dispatch.secret_key_base                : 4660dc507b7141164309c2e7445eadc47e15a04e289ef6b8798612c90c37db2d8bb0bdda3a2ede0556be882b9b2b25838744465e1dde0e0895850876dce394a5
  * action_dispatch.secret_token                   :
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * puma.config                                    : #<Puma::Configuration:0x0000556c2c9f2a70>
  * puma.socket                                    : #<TCPSocket:0x00007fc63db17b18>
  * rack.after_reply                               : []
  * rack.errors                                    : #<IO:0x0000556c2bcad860>
  * rack.hijack                                    : #<Puma::Client:0x00007fc63db17af0>
  * rack.hijack?                                   : true
  * rack.input                                     : #<Puma::NullIO:0x0000556c2c6aaed0>
  * rack.multiprocess                              : false
  * rack.multithread                               : true
  * rack.request.cookie_hash                       : {"_mrt-dash_session"=>"S3pmUE84djQrMnVRbW9xSTQ0R3JYSGdaVDdZZzZoMFIyVWxUb0ZHckNOU3U1YjIzK2dkQmxaYjVCRDZ0ZHl5NXdpYk42SXEvblVJTWoxY1h6cjR5YTNaWVFUanA2Q0c1RmJVelo3WU5jVEh2ZHl2WFc1OHExUGNIM2lueTBSZGt0WW9ndUZTRmtzd3V0ZXExRlBVZlp1WTBYT1ZGd25OSU9DS2x3d1NWNWJWcHRIVHNndGsvWDc0dG5KWVZnMmR5UzlIcFBTb20xeEhHbGNNb...
  * rack.request.cookie_string                     : _mrt-dash_session=S3pmUE84djQrMnVRbW9xSTQ0R3JYSGdaVDdZZzZoMFIyVWxUb0ZHckNOU3U1YjIzK2dkQmxaYjVCRDZ0ZHl5NXdpYk42SXEvblVJTWoxY1h6cjR5YTNaWVFUanA2Q0c1RmJVelo3WU5jVEh2ZHl2WFc1OHExUGNIM2lueTBSZGt0WW9ndUZTRmtzd3V0ZXExRlBVZlp1WTBYT1ZGd25OSU9DS2x3d1NWNWJWcHRIVHNndGsvWDc0dG5KWVZnMmR5UzlIcFBTb20xeEhHbGNNbjA5dFBwbUVUSEVFdzAyOTBaeEltUHY5SGg0VCs0VVQ2VFQyU3pPYUx2YURHS1FvYTh5bC9vMVBjUHFOc3puS3lKd3c1UVd0SjJFUUY1K2d2QTZiaklwQVJFWDZQakZHWFBHbDdMajNHYlBvMmFWMXdPUVg3Q0ptOHY3VnVPelA4NzMxblptcC9kbm1UbUlibXBjK0t4aDI5V1JFSzd3bHFpajJqeGwvdVBZeDZxSE9aLS1sSENEczVUQUpVWkgzR0pFajdPS2JnPT0%3D--3d4f6f77902c2e303eb220b37f66d860c813c50d
  * rack.request.query_hash                        : {"page"=>"314'A=0"}
  * rack.request.query_string                      : page=314'A=0
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x00007fc63d5cb998>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x00007fc63d5cb948>
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 3]

-------------------------------
Backtrace:
-------------------------------

  /apps/dpr2/local/lib/ruby/2.4.0/delegate.rb:85:in `Integer'
  /apps/dpr2/local/lib/ruby/2.4.0/delegate.rb:85:in `call'
  /apps/dpr2/local/lib/ruby/2.4.0/delegate.rb:85:in `method_missing'
  app/controllers/collection_controller.rb:55:in `find_all'
  app/controllers/collection_controller.rb:38:in `index'
```

**Comment by mreyescdl** [comment]
will test on dev

**Comment by dmolesUC3** [comment]
Fixed in a57c22e
