### ISSUE TITLE
SQL error in Group::object_count

### ISSUE THREAD

**Issue by dmolesUC3** [CDLUC3/mrt-dashboard#8]
```
An ActionView::Template::Error occurred in collection#object_count:

  Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DISTINCT(inv_objects.id)) AS count
  FROM inv_objects
       INNER JOIN inv_coll' at line 1: SELECT COUNT (DISTINCT(inv_objects.id)) AS count
  FROM inv_objects
       INNER JOIN inv_collections_inv_objects
               ON inv_objects.id = inv_collections_inv_objects.inv_object_id
WHERE ((inv_collections_inv_objects.inv_collection_id = 13))

  app/models/group.rb:80:in `object_count'


-------------------------------
Request:
-------------------------------

  * URL        : http://merritt-dev.cdlib.org/collection/object_count?group=dash_cdl
  * HTTP Method: GET
  * IP address : 128.48.204.175
  * Parameters : {"group"=>"dash_cdl", "controller"=>"collection", "action"=>"object_count"}
  * Timestamp  : 2018-07-09 23:58:16 UTC
  * Server : uc3-mrtui-dev
  * Rails root : /apps/dpr2/apps/ui/releases/20180709235727
  * Process: 20272

-------------------------------
Session:
-------------------------------

  * session id: "50c2fe0d81f7c729481e108251ef7c2a"
  * data: {"session_id"=>"50c2fe0d81f7c729481e108251ef7c2a",
   "_csrf_token"=>"vAquk6QGSNf57bwuVBFL74Tuu19FNorudjhJSuILDOw=",
   "expiry_time"=>2018-07-09 16:58:01 -0700,
   "uid"=>"mreyes",
   "flash"=>
    {"discard"=>["notice"], "flashes"=>{"notice"=>"Login was successful"}},
   "user_displayname"=>"Mark Reyes",
   "group_id"=>"dash_cdl",
   "group_ark"=>"ark:/99999/fk4pg1qtb",
   "group_description"=>"DASH CDL collection"}

-------------------------------
Environment:
-------------------------------

  * GATEWAY_INTERFACE                              : CGI/1.2
  * HTTP_ACCEPT                                    : text/javascript, text/html, application/xml, text/xml, */*
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, sdch
  * HTTP_ACCEPT_LANGUAGE                           : en-US,en;q=0.8
  * HTTP_CONNECTION                                : Keep-Alive
  * HTTP_COOKIE                                    : __utma=29472237.1688875604.1511826347.1525724052.1529514867.9; __utmz=29472237.1529514867.9.3.utmccn=(referral)|utmcsr=intracdl.cdlib.org|utmcct=/|utmcmd=referral; _ga=GA1.2.2091239646.1496438387; _mrt-dash_session=blBqSzUzeHNNSFhVZFN3SFNFcEoxWWw0TmRHR0cvNnY3M0tvaHR3RDBCNGpxZzhYM0prd0ZhU1IveUwrZWN4WTQxTkpxVDdoa1hZazNvV2NEaFJoK016eklDREFmZ1N0VmJmQ2hHK3JMdktpMGZVd2tCbjZvY3EwMndtUktXd3c5ZXRRdUgvT3VTWjFkZ1RqRXNVS21Qb0hrNDJxbGo1em5iaXpuSGxzTTgvb2lRTnpuWEZVUDRzc2FnTnVLSERjSkNIUFp3c3I2aFNWaVhVU1VTQ0EvQk5DL3pnU1BpTlRpWDhwR3dHZHczRTlGWDg3bHFIUU1lK3hpMW5SRFBaeFVaTitjcTZ6cjNleitZMnMvcXBGZVRuclpXenJzQ0xVbGF5WWc0QmxqU2tVQmVrSDFUbHpORDd6OFBRQ0dHRGsrWEpkTEUwTFI4SGVQQmdWMzBlOWRIcGl6SlNIR3h4Rkk1VVZqZi9EcCtyME9LQ3RSeDJpNDYrTWNjQUo5MFIvVUVGYStZYW5JbjJpMlNBTUc3YlY3MkdJaUgvdC93alVUYUt5Z0h5L3A3QU9aTjZWK1pPWjhUVW50WkJEVURSTGo1WkxOZEh1dW9TYm0yYTN4NHBmOVBUNldNNFNWVlplSEU4NDM0Y29uMFg2WmdyVlQ4UytUbnVVV3R3akplRUVHN0s1eS9WWllXaXgzQnpxdVpBQytWOGE3SmFqeTlDY3NSeGNQVUdhLzRFMzErRFR0K1NDQVhORXlTd0ZOM0ZrMHFnODVIUlpnVTZjUVRrUU91d1FQaDUxL0JrbC9UWU9USmZqdWIvME1LTGRNWVFCUmZFdFpIOUpYWGxBOUJrQ1VyRS9qZ1hNMjNVWk5CNjVYbDhYZXlqNUZFUVZKZG1WZjlJQXhRU25SWGcxOElZOGhLdlYvWk9qQ29jUktxc25FYUJ6NGZPdXYvREoybThuMmtBdzNTc0tRQWJnMS94dEk1UkZMVVJRQkNiTkJjSktkMTArcndrSU5UaTIydGUyZlY4U3FGNnVGRVJrckswMEtqekpwUT09LS1VSHQzQ09MdVZBRXB0TnB1Rml0S2hRPT0%3D--20563df5efc8f4065b3f01ae5b8034f3714b3916
  * HTTP_DNT                                       : 1
  * HTTP_HOST                                      : ui-aws-dev.cdlib.org:26181
  * HTTP_REFERER                                   : http://merritt-dev.cdlib.org/m/dash_cdl
  * HTTP_USER_AGENT                                : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36
  * HTTP_VERSION                                   : HTTP/1.1
  * HTTP_X_FORWARDED_FOR                           : 128.48.204.175
  * HTTP_X_FORWARDED_HOST                          : merritt-dev.cdlib.org
  * HTTP_X_FORWARDED_SERVER                        : merritt-dev.cdlib.org
  * HTTP_X_PROTOTYPE_VERSION                       : 1.6.1
  * HTTP_X_REQUESTED_WITH                          : XMLHttpRequest
  * ORIGINAL_FULLPATH                              : //collection/object_count?group=dash_cdl
  * ORIGINAL_SCRIPT_NAME                           :
  * PATH_INFO                                      : /collection/object_count
  * QUERY_STRING                                   : group=dash_cdl
  * REMOTE_ADDR                                    : 172.31.17.174
  * REQUEST_METHOD                                 : GET
  * REQUEST_PATH                                   : //collection/object_count
  * REQUEST_URI                                    : //collection/object_count?group=dash_cdl
  * ROUTES_47188803170780_SCRIPT_NAME              :
  * SCRIPT_NAME                                    :
  * SERVER_NAME                                    : ui-aws-dev.cdlib.org
  * SERVER_PORT                                    : 26181
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : puma 3.8.2 Sassy Salamander
  * action_controller.instance                     : #<CollectionController:0x00007f92698fc430>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x000055d60031e4b8>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x00007f9269929548>
  * action_dispatch.cookies_digest                 :
  * action_dispatch.cookies_serializer             :
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x000055d600922f08>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x000055d5ffab6ca8>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 128.48.204.175
  * action_dispatch.request.accepts                : [#<Mime::Type:0x000055d5ff21d290 @synonyms=["application/javascript", "application/x-javascript"], @symbol=:js, @string="text/javascript", @hash=-1668821124619714872>, #<Mime::Type:0x000055d5ff21ddf8 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-4528603634334523139>...
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [#<Mime::Type:0x000055d5ff21d290 @synonyms=["application/javascript", "application/x-javascript"], @symbol=:js, @string="text/javascript", @hash=-1668821124619714872>, #<Mime::Type:0x000055d5ff21ddf8 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-4528603634334523139>...
  * action_dispatch.request.parameters             : {"group"=>"dash_cdl", "controller"=>"collection", "action"=>"object_count"}
  * action_dispatch.request.path_parameters        : {:controller=>"collection", :action=>"object_count"}
  * action_dispatch.request.query_parameters       : {"group"=>"dash_cdl"}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"50c2fe0d81f7c729481e108251ef7c2a", "_csrf_token"=>"vAquk6QGSNf57bwuVBFL74Tuu19FNorudjhJSuILDOw=", "expiry_time"=>2018-07-09 16:58:01 -0700, "uid"=>"mreyes", "flash"=>{"discard"=>["notice"], "flashes"=>{"notice"=>"Login was successful"}}, "user_displayname"=>"Mark Reyes", "group_id"=>...
  * action_dispatch.request_id                     : 286e405c-e6ed-47aa-829c-86fd2b7ec4b5
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x000055d5ffb363b8>
  * action_dispatch.secret_key_base                : d943251edf4019f3094cf7c0f17c7ba40fe0418a63e692baae21069184e45d8c672108b24d00533ed87a45a6cec5ba2bc21d074177bdbc158fc60be32c2eb444
  * action_dispatch.secret_token                   :
  * action_dispatch.show_detailed_exceptions       : true
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * puma.config                                    : #<Puma::Configuration:0x000055d5fe056638>
  * puma.socket                                    : #<TCPSocket:0x000055d600f4f160>
  * rack.after_reply                               : []
  * rack.errors                                    : #<IO:0x000055d5fd2fd860>
  * rack.hijack                                    : #<Puma::Client:0x000055d600f4f138>
  * rack.hijack?                                   : true
  * rack.input                                     : #<Puma::NullIO:0x000055d5fdcb7a68>
  * rack.multiprocess                              : false
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {"__utma"=>"29472237.1688875604.1511826347.1525724052.1529514867.9", "__utmz"=>"29472237.1529514867.9.3.utmccn=(referral)|utmcsr=intracdl.cdlib.org|utmcct=/|utmcmd=referral", "_ga"=>"GA1.2.2091239646.1496438387", "_mrt-dash_session"=>"blBqSzUzeHNNSFhVZFN3SFNFcEoxWWw0TmRHR0cvNnY3M0tvaHR3RDBCNGpxZzhYM...
  * rack.request.cookie_string                     : __utma=29472237.1688875604.1511826347.1525724052.1529514867.9; __utmz=29472237.1529514867.9.3.utmccn=(referral)|utmcsr=intracdl.cdlib.org|utmcct=/|utmcmd=referral; _ga=GA1.2.2091239646.1496438387; _mrt-dash_session=blBqSzUzeHNNSFhVZFN3SFNFcEoxWWw0TmRHR0cvNnY3M0tvaHR3RDBCNGpxZzhYM0prd0ZhU1IveUwrZWN4WTQxTkpxVDdoa1hZazNvV2NEaFJoK016eklDREFmZ1N0VmJmQ2hHK3JMdktpMGZVd2tCbjZvY3EwMndtUktXd3c5ZXRRdUgvT3VTWjFkZ1RqRXNVS21Qb0hrNDJxbGo1em5iaXpuSGxzTTgvb2lRTnpuWEZVUDRzc2FnTnVLSERjSkNIUFp3c3I2aFNWaVhVU1VTQ0EvQk5DL3pnU1BpTlRpWDhwR3dHZHczRTlGWDg3bHFIUU1lK3hpMW5SRFBaeFVaTitjcTZ6cjNleitZMnMvcXBGZVRuclpXenJzQ0xVbGF5WWc0QmxqU2tVQmVrSDFUbHpORDd6OFBRQ0dHRGsrWEpkTEUwTFI4SGVQQmdWMzBlOWRIcGl6SlNIR3h4Rkk1VVZqZi9EcCtyME9LQ3RSeDJpNDYrTWNjQUo5MFIvVUVGYStZYW5JbjJpMlNBTUc3YlY3MkdJaUgvdC93alVUYUt5Z0h5L3A3QU9aTjZWK1pPWjhUVW50WkJEVURSTGo1WkxOZEh1dW9TYm0yYTN4NHBmOVBUNldNNFNWVlplSEU4NDM0Y29uMFg2WmdyVlQ4UytUbnVVV3R3akplRUVHN0s1eS9WWllXaXgzQnpxdVpBQytWOGE3SmFqeTlDY3NSeGNQVUdhLzRFMzErRFR0K1NDQVhORXlTd0ZOM0ZrMHFnODVIUlpnVTZjUVRrUU91d1FQaDUxL0JrbC9UWU9USmZqdWIvME1LTGRNWVFCUmZFdFpIOUpYWGxBOUJrQ1VyRS9qZ1hNMjNVWk5CNjVYbDhYZXlqNUZFUVZKZG1WZjlJQXhRU25SWGcxOElZOGhLdlYvWk9qQ29jUktxc25FYUJ6NGZPdXYvREoybThuMmtBdzNTc0tRQWJnMS94dEk1UkZMVVJRQkNiTkJjSktkMTArcndrSU5UaTIydGUyZlY4U3FGNnVGRVJrckswMEtqekpwUT09LS1VSHQzQ09MdVZBRXB0TnB1Rml0S2hRPT0%3D--20563df5efc8f4065b3f01ae5b8034f3714b3916
  * rack.request.query_hash                        : {"group"=>"dash_cdl"}
  * rack.request.query_string                      : group=dash_cdl
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x00007f92698fd290>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x00007f92698fd240>
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 3]

-------------------------------
Backtrace:
-------------------------------

  app/models/group.rb:80:in `object_count'
  app/views/collection/_object_count.html.erb:2:in `block in _app_views_collection__object_count_html_erb__4261078844740083313_47188818314980'
  app/views/collection/_object_count.html.erb:1:in `_app_views_collection__object_count_html_erb__4261078844740083313_47188818314980'
  /apps/dpr2/local/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
  app/controllers/collection_controller.rb:21:in `object_count'
```

**Comment by dmolesUC3** [comment]
Fixed in [2018.3.3](https://github.com/CDLUC3/mrt-dashboard/releases/tag/2018.3.3).
